export const punctualityQuotes = [
  "Punctuality is not just about being on time, it’s about respecting your commitments.",
  "Better three hours too soon than a minute too late. - William Shakespeare",
  "Punctuality is the soul of business. - Thomas Chandler Haliburton",
  "Being on time is a reflection of your integrity and discipline.",
  "Punctuality is the first step towards success.",
  "Respect for time is respect for others.",
  "Punctuality is a virtue that builds reliability and trust.",
  "Time is what we want most, but what we use worst. - William Penn",
  "Being early is on time; being on time is late.",
  "Success is built on the habit of meeting deadlines.",
  "A man who dares to waste one hour of time has not discovered the value of life. - Charles Darwin",
  "Punctuality is the politeness of kings. - Louis XVIII",
  "When you are late, you steal someone else’s time.",
  "The secret of success in life is for a man to be ready for his opportunity when it comes. - Benjamin Disraeli",
  "Lost time is never found again. - Benjamin Franklin",
  "The habit of being prompt once formed extends to everything. - William Makepeace Thackeray",
  "Timeliness is a sign of professionalism and discipline.",
  "Respect your appointments, and others will respect you.",
  "Your reputation is built on your ability to honor commitments on time.",
  "Punctuality is the art of guessing how late the other fellow is going to be. - Evan Esar",
  "Arriving late is a way of saying that your own time is more valuable than the time of the person who waited for you. - Karen Joy Fowler",
  "The trouble with being punctual is that nobody’s there to appreciate it. - Franklin P. Jones",
  "Punctuality is the thief of time. - Oscar Wilde",
  "Time is a created thing. To say 'I don’t have time' is like saying, 'I don’t want to.' - Lao Tzu",
  "If you want to be respected, be on time. If you want to be ignored, be late.",
];

export const workMotivationQuotes = [
  "The secret of getting ahead is getting started. - Mark Twain",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do what you have to do until you can do what you want to do. - Oprah Winfrey",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Dream big. Start small. Act now.",
  "Your only limit is your mind.",
  "Hard work beats talent when talent doesn’t work hard. - Tim Notke",
  "Don’t count the days, make the days count. - Muhammad Ali",
  "Success is not in what you have, but who you are. - Bo Bennett",
  "What you do today can improve all your tomorrows. - Ralph Marston",
  "Success is getting what you want. Happiness is wanting what you get. - Dale Carnegie",
  "The best preparation for good work tomorrow is to do good work today. - Elbert Hubbard",
  "Do something today that your future self will thank you for.",
  "Act as if what you do makes a difference. It does. - William James",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Great things never come from comfort zones.",
  "Discipline is the bridge between goals and accomplishment. - Jim Rohn",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Small daily improvements are the key to staggering long-term results.",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Doubt kills more dreams than failure ever will. - Suzy Kassem",
  "Push yourself, because no one else is going to do it for you.",
  "A little progress each day adds up to big results.",
  "Strive for progress, not perfection.",
  "Your energy introduces you before you even speak.",
  "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
  "If you want something you’ve never had, you must be willing to do something you’ve never done. - Thomas Jefferson",
  "Some people dream of success, while others wake up and work hard at it.",
  "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
  "Success is not for the lazy.",
  "Make today so awesome that yesterday gets jealous.",
  "Difficult roads often lead to beautiful destinations.",
  "Opportunities are usually disguised as hard work, so most people don’t recognize them. - Ann Landers",
  "Rise up. Start fresh. See the bright opportunity in each new day.",
];

export const invalid_characters = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  "@",
  "!",
  "#",
  "$",
  "%",
  "^",
  "&",
  "*",
  "(",
  ")",
  "-",
  "+",
  "=",
  "{",
  "}",
  "[",
  "]",
  ":",
  '"',
  "'",
  "/",
  "?",
  ",",
  ".",
  "<",
  ">",
];
